# Generated by Django 6.0.3 on 2026-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
