# Generated by Django 6.0.3 on 2026-04-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0003_likeditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeditem',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.RemoveField(
            model_name='likeditem',
            name='liked_at',
        ),
        migrations.AddField(
            model_name='likeditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
