# Generated by Django 6.0.3 on 2026-04-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovie', '0004_rename_name_likeditem_movie_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
